# Generated by Django 4.1.4 on 2023-01-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_classes', '0002_studentclass_id_alter_studentclass_class_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentclass',
            unique_together=set(),
        ),
    ]
