# Generated by Django 4.1.4 on 2023-01-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_classes', '0003_alter_studentclass_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='class_name',
            field=models.CharField(help_text='Eg- Third, Fouth,Sixth etc', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='studentclass',
            unique_together={('class_name', 'section')},
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='id',
        ),
    ]
