# Generated by Django 4.1.4 on 2023-01-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_classes', '__first__'),
        ('results', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('subject_creation_date', models.DateTimeField(auto_now_add=True)),
                ('subject_update_date', models.DateTimeField(auto_now=True)),
                ('results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sub', to='results.declareresult')),
            ],
            options={
                'unique_together': {('subject_name', 'subject_code')},
            },
        ),
        migrations.CreateModel(
            name='SubjectCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_classes.studentclass')),
                ('select_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'unique_together': {('select_class', 'select_subject')},
            },
        ),
    ]
